export const plansData = [
    {
      containerClass: "relative w-[800px] h-[800px] rounded-full md:top-[125px] lg:top-[111px] flex justify-center items-center z-10",
      circleClass: "absolute w-full h-full inset-0 !rounded-full border-4 rotating-circle",
      plans: [
        {
          wrapperClass: "absolute flex justify-center items-center flex-col rounded-full w-[70px] h-[70px] plan-spear plan-spear-one",
          percentage: "0.2%",
          title: "Plan 1",
          descClass: "absolute plan-spear-desc plan-spear-desc-one",
          descContentClass: "flex justify-center items-center gap-2 plan-spear-desc-content plan-spear-desc-one-content absolute",
          min: "MIN €20.00",
          mainPercentage: "0.2%",
          duration: "hourly for 96 hours",
          range: "$10.00-$500.00",
          currency: "USD",
        },
        {
          wrapperClass: "absolute flex justify-center items-center flex-col rounded-full w-[70px] h-[70px] plan-spear plan-spear-two",
          percentage: "6.1%",
          title: "Plan 2",
          descClass: "absolute plan-spear-desc plan-spear-desc-two",
          descContentClass: "flex justify-center items-center gap-2 plan-spear-desc-content plan-spear-desc-two-content absolute",
          min: "MIN €40.00",
          mainPercentage: "0.2%",
          duration: "hourly for 96 hours",
          range: "$10.00-$500.00",
          currency: "USD",
        },
      ],
    },
    {
      containerClass: "absolute w-[600px] h-[600px] rounded-full md:top-[394px] lg:top-[348px] flex justify-center items-center z-20",
      circleClass: "absolute w-full h-full inset-0 !rounded-full border-4 rotating-circle",
      plans: [
        {
          wrapperClass: "absolute flex justify-center items-center flex-col rounded-full w-[70px] h-[70px] plan-spear plan-spear-three",
          percentage: "2.4%",
          title: "Plan 3",
          descClass: "absolute plan-spear-desc plan-spear-desc-three",
          descContentClass: "flex justify-center items-center gap-2 plan-spear-desc-content plan-spear-desc-three-content absolute",
          min: "MIN €60.00",
          mainPercentage: "0.2%",
          duration: "hourly for 96 hours",
          range: "$10.00-$500.00",
          currency: "USD",
        },
        {
          wrapperClass: "absolute flex justify-center items-center flex-col rounded-full w-[70px] h-[70px] plan-spear plan-spear-four",
          percentage: "8.4%",
          title: "Plan 4",
          descClass: "absolute plan-spear-desc plan-spear-desc-four",
          descContentClass: "flex justify-center items-center gap-2 plan-spear-desc-content plan-spear-desc-four-content absolute",
          min: "MIN €80.00",
          mainPercentage: "0.2%",
          duration: "hourly for 96 hours",
          range: "$10.00-$500.00",
          currency: "USD",
        },
      ],
    },
    {
      containerClass: "absolute w-[400px] h-[400px] rounded-full md:top-[502px] lg:top-[451px] flex justify-center items-center z-20",
      circleClass: "absolute w-full h-full inset-0 !rounded-full border-4 rotating-circle",
      plans: [
        {
          wrapperClass: "absolute flex justify-center items-center flex-col rounded-full w-[70px] h-[70px] plan-spear plan-spear-five",
          percentage: "2.4%",
          title: "Plan 5",
          descClass: "absolute plan-spear-desc plan-spear-desc-five",
          descContentClass: "flex justify-center items-center gap-2 plan-spear-desc-content plan-spear-desc-five-content absolute",
          min: "MIN €30.00",
          mainPercentage: "0.2%",
          duration: "hourly for 96 hours",
          range: "$10.00-$500.00",
          currency: "USD",
        },
        {
          wrapperClass: "absolute flex justify-center items-center flex-col rounded-full w-[70px] h-[70px] plan-spear plan-spear-six",
          percentage: "8.4%",
          title: "Plan 6",
          descClass: "absolute plan-spear-desc plan-spear-desc-six",
          descContentClass: "flex justify-center items-center gap-2 plan-spear-desc-content plan-spear-desc-six-content absolute",
          min: "MIN €90.00",
          mainPercentage: "0.2%",
          duration: "hourly for 96 hours",
          range: "$10.00-$500.00",
          currency: "USD",
        },
      ],
    },
  ];
  